name: CI

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

jobs:
  lint-and-format:
    name: Linting & Formatting
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: pnpm/action-setup@v4
        with:
          run_install: true

      - name: Lint code
        run: pnpm lint

      - name: Run Prettier Check
        run: pnpm format:check

  tests:
    name: Unit tests
    needs: lint-and-format
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: pnpm/action-setup@v4
        with:
          run_install: true

      - name: Run Unit tests
        run: pnpm test:unit

      - name: Create test coverage
        run: pnpm test:unit:coverage

      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v5
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
    
  integration-tests:
    name: Integration tests
    runs-on: ubuntu-latest
    needs: lint-and-format
    env:
      POSTGRES_DB_CONNECTION_STRING: postgresql://username:password@localhost:5432/integration
      POSTGRES_USER: username
      POSTGRES_PASSWORD: password
      POSTGRES_DB: integration
      JWT_SECRET: jwt-integration-secret
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: pnpm/action-setup@v4
        with:
          run_install: true

      - name: Prepare docker-compose plugin
        uses: ./.github/actions/docker-compose

      - name: Run tests
        run: pnpm test:integration